In [1]:
print("Let's Start")

Let's Start

In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [3]:
df = pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv')

In [4]:
X = df.drop(columns=['price'])
y = df['price']

In [5]:
# Applying the log1p transformation to the target variable
y_transformed = np.log1p(y)

In [6]:
# import automac
# afe  = automac.feature_engineering.FeatureEngineering(X , y_transformed)

In [7]:
from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

In [8]:
from category_encoders import TargetEncoder
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [53]:
X.head()

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [54]:
x_transed , encoder = afe.encode_categories(['agePossession' , 'luxury_category' , 'floor_category' , 'sector' , 'property_type' , 'balcony'])

In [55]:
x_s , scaler = afe.scale_features(['built_up_area'])

In [59]:
x_s.info()

<class 'pandas.DataFrame'>
RangeIndex: 3554 entries, 0 to 3553
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_type    3554 non-null   float64
 1   sector           3554 non-null   float64
 2   bedRoom          3554 non-null   float64
 3   bathroom         3554 non-null   float64
 4   balcony          3554 non-null   float64
 5   agePossession    3554 non-null   float64
 6   built_up_area    3554 non-null   float64
 7   servant room     3554 non-null   float64
 8   store room       3554 non-null   float64
 9   furnishing_type  3554 non-null   float64
 10  luxury_category  3554 non-null   float64
 11  floor_category   3554 non-null   float64
dtypes: float64(12)
memory usage: 333.3 KB

In [60]:
from sklearn.linear_model import LinearRegression , Ridge , Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingRegressor , RandomForestRegressor , AdaBoostRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor

In [79]:
models = [LinearRegression() , Ridge() , Lasso() , DecisionTreeRegressor() , SVR() , GradientBoostingRegressor() , RandomForestRegressor() , AdaBoostRegressor() , XGBRegressor() , CatBoostRegressor() , LGBMRegressor()]
names   = ['LinearRegression' , 'Ridge' , 'Lasso' , 'DecisionTreeRegressor' , 'SVR' , 'GradientBoostingRegressor' , 'RandomForestRegressor' , 'AdaBoostRegressor' , 'XGBRegressor' , 'CatBoostRegressor' , 'LGBMRegressor']

In [80]:
ra = automac.analyser.RegressionAnalyser(x=x_s , y=y_transformed)

In [82]:
scores = {}
for i in range(len(models)):
    score = ra.regression_metrics(model=models[i])
    scores[names[i]] = score

Learning rate set to 0.047282
0:	learn: 0.5373051	total: 1.65ms	remaining: 1.65s
1:	learn: 0.5197666	total: 2.48ms	remaining: 1.24s
2:	learn: 0.5022029	total: 3.29ms	remaining: 1.09s
3:	learn: 0.4848223	total: 4.98ms	remaining: 1.24s
4:	learn: 0.4688345	total: 5.75ms	remaining: 1.15s
5:	learn: 0.4534298	total: 6.49ms	remaining: 1.07s
6:	learn: 0.4390343	total: 7.13ms	remaining: 1.01s
7:	learn: 0.4250292	total: 7.92ms	remaining: 982ms
8:	learn: 0.4110929	total: 8.69ms	remaining: 957ms
9:	learn: 0.3990776	total: 9.5ms	remaining: 941ms
10:	learn: 0.3872630	total: 10.4ms	remaining: 934ms
11:	learn: 0.3758566	total: 11.2ms	remaining: 921ms
12:	learn: 0.3655315	total: 11.9ms	remaining: 903ms
13:	learn: 0.3555138	total: 12.8ms	remaining: 903ms
14:	learn: 0.3461240	total: 13.6ms	remaining: 895ms
15:	learn: 0.3368887	total: 14.5ms	remaining: 890ms
16:	learn: 0.3284814	total: 15.3ms	remaining: 885ms
17:	learn: 0.3206818	total: 16.2ms	remaining: 882ms
18:	learn: 0.3132016	total: 17ms	remaining: 877ms
19:	learn: 0.3065479	total: 17.8ms	remaining: 873ms
20:	learn: 0.3001809	total: 18.6ms	remaining: 868ms
21:	learn: 0.2940419	total: 19.4ms	remaining: 862ms
22:	learn: 0.2876284	total: 20.2ms	remaining: 858ms
23:	learn: 0.2817832	total: 21ms	remaining: 853ms
24:	learn: 0.2770525	total: 21.8ms	remaining: 850ms
25:	learn: 0.2717787	total: 22.6ms	remaining: 846ms
26:	learn: 0.2669532	total: 23.4ms	remaining: 842ms
27:	learn: 0.2625292	total: 24.2ms	remaining: 839ms
28:	learn: 0.2584767	total: 25.2ms	remaining: 844ms
29:	learn: 0.2545747	total: 26.1ms	remaining: 843ms
30:	learn: 0.2504228	total: 26.9ms	remaining: 840ms
31:	learn: 0.2463836	total: 27.7ms	remaining: 837ms
32:	learn: 0.2429853	total: 28.5ms	remaining: 835ms
33:	learn: 0.2397267	total: 29.3ms	remaining: 833ms
34:	learn: 0.2364018	total: 30.1ms	remaining: 831ms
35:	learn: 0.2335915	total: 31.1ms	remaining: 832ms
36:	learn: 0.2307105	total: 31.8ms	remaining: 828ms
37:	learn: 0.2280987	total: 32.6ms	remaining: 827ms
38:	learn: 0.2257952	total: 33.5ms	remaining: 825ms
39:	learn: 0.2234040	total: 34.5ms	remaining: 827ms
40:	learn: 0.2213045	total: 35.3ms	remaining: 826ms
41:	learn: 0.2190040	total: 36.2ms	remaining: 825ms
42:	learn: 0.2173367	total: 37.1ms	remaining: 825ms
43:	learn: 0.2156193	total: 37.9ms	remaining: 823ms
44:	learn: 0.2139079	total: 39.2ms	remaining: 831ms
45:	learn: 0.2124222	total: 40.1ms	remaining: 831ms
46:	learn: 0.2107469	total: 40.9ms	remaining: 829ms
47:	learn: 0.2092709	total: 41.8ms	remaining: 828ms
48:	learn: 0.2076321	total: 42.6ms	remaining: 826ms
49:	learn: 0.2063290	total: 43.4ms	remaining: 824ms
50:	learn: 0.2050617	total: 46.1ms	remaining: 858ms
51:	learn: 0.2037977	total: 47ms	remaining: 857ms
52:	learn: 0.2026380	total: 48ms	remaining: 857ms
53:	learn: 0.2015425	total: 49.2ms	remaining: 862ms
54:	learn: 0.2004152	total: 50.1ms	remaining: 861ms
55:	learn: 0.1994196	total: 51ms	remaining: 859ms
56:	learn: 0.1985915	total: 51.8ms	remaining: 857ms
57:	learn: 0.1975514	total: 52.7ms	remaining: 855ms
58:	learn: 0.1967075	total: 53.5ms	remaining: 853ms
59:	learn: 0.1960188	total: 54.3ms	remaining: 850ms
60:	learn: 0.1954118	total: 55ms	remaining: 847ms
61:	learn: 0.1947290	total: 56ms	remaining: 847ms
62:	learn: 0.1941027	total: 56.8ms	remaining: 845ms
63:	learn: 0.1933125	total: 57.7ms	remaining: 844ms
64:	learn: 0.1923691	total: 58.5ms	remaining: 841ms
65:	learn: 0.1918618	total: 59.3ms	remaining: 839ms
66:	learn: 0.1911228	total: 60ms	remaining: 836ms
67:	learn: 0.1905277	total: 60.8ms	remaining: 833ms
68:	learn: 0.1899112	total: 61.5ms	remaining: 830ms
69:	learn: 0.1892817	total: 62.3ms	remaining: 828ms
70:	learn: 0.1887141	total: 63.1ms	remaining: 826ms
71:	learn: 0.1881726	total: 63.9ms	remaining: 823ms
72:	learn: 0.1877063	total: 64.7ms	remaining: 821ms
73:	learn: 0.1873311	total: 65.4ms	remaining: 818ms
74:	learn: 0.1868391	total: 66.1ms	remaining: 816ms
75:	learn: 0.1864199	total: 66.9ms	remaining: 814ms
76:	learn: 0.1860856	total: 67.8ms	remaining: 813ms
77:	learn: 0.1857275	total: 70.7ms	remaining: 836ms
78:	learn: 0.1854156	total: 72.3ms	remaining: 843ms
79:	learn: 0.1850037	total: 73.3ms	remaining: 843ms
80:	learn: 0.1845667	total: 75.9ms	remaining: 861ms
81:	learn: 0.1842532	total: 76.9ms	remaining: 861ms
82:	learn: 0.1838926	total: 77.8ms	remaining: 859ms
83:	learn: 0.1834882	total: 78.7ms	remaining: 858ms
84:	learn: 0.1831568	total: 79.6ms	remaining: 856ms
85:	learn: 0.1828134	total: 80.6ms	remaining: 857ms
86:	learn: 0.1824012	total: 81.5ms	remaining: 855ms
87:	learn: 0.1821169	total: 82.3ms	remaining: 852ms
88:	learn: 0.1817136	total: 83.1ms	remaining: 851ms
89:	learn: 0.1813089	total: 84.1ms	remaining: 851ms
90:	learn: 0.1810493	total: 85.1ms	remaining: 850ms
91:	learn: 0.1807506	total: 86ms	remaining: 848ms
92:	learn: 0.1804649	total: 86.8ms	remaining: 847ms
93:	learn: 0.1800414	total: 87.6ms	remaining: 844ms
94:	learn: 0.1796181	total: 88.3ms	remaining: 842ms
95:	learn: 0.1793592	total: 89.1ms	remaining: 839ms
96:	learn: 0.1791462	total: 90.1ms	remaining: 838ms
97:	learn: 0.1787847	total: 90.9ms	remaining: 836ms
98:	learn: 0.1785308	total: 91.7ms	remaining: 835ms
99:	learn: 0.1782778	total: 92.6ms	remaining: 833ms
100:	learn: 0.1780196	total: 93.4ms	remaining: 831ms
101:	learn: 0.1777211	total: 94.1ms	remaining: 828ms
102:	learn: 0.1773300	total: 94.9ms	remaining: 827ms
103:	learn: 0.1770328	total: 95.7ms	remaining: 825ms
104:	learn: 0.1767970	total: 96.5ms	remaining: 823ms
105:	learn: 0.1765617	total: 97.3ms	remaining: 821ms
106:	learn: 0.1763381	total: 98.1ms	remaining: 818ms
107:	learn: 0.1762494	total: 98.5ms	remaining: 814ms
108:	learn: 0.1759989	total: 99.4ms	remaining: 812ms
109:	learn: 0.1757445	total: 100ms	remaining: 810ms
110:	learn: 0.1754680	total: 101ms	remaining: 808ms
111:	learn: 0.1753214	total: 102ms	remaining: 807ms
112:	learn: 0.1751278	total: 103ms	remaining: 805ms
113:	learn: 0.1749504	total: 103ms	remaining: 803ms
114:	learn: 0.1745655	total: 104ms	remaining: 801ms
115:	learn: 0.1742377	total: 105ms	remaining: 799ms
116:	learn: 0.1740766	total: 106ms	remaining: 797ms
117:	learn: 0.1739466	total: 106ms	remaining: 795ms
118:	learn: 0.1736383	total: 107ms	remaining: 793ms
119:	learn: 0.1733574	total: 108ms	remaining: 791ms
120:	learn: 0.1731831	total: 109ms	remaining: 792ms
121:	learn: 0.1729720	total: 110ms	remaining: 792ms
122:	learn: 0.1727883	total: 111ms	remaining: 790ms
123:	learn: 0.1725664	total: 111ms	remaining: 788ms
124:	learn: 0.1723560	total: 112ms	remaining: 786ms
125:	learn: 0.1721704	total: 113ms	remaining: 785ms
126:	learn: 0.1719103	total: 114ms	remaining: 783ms
127:	learn: 0.1716212	total: 115ms	remaining: 781ms
128:	learn: 0.1714714	total: 115ms	remaining: 779ms
129:	learn: 0.1712498	total: 116ms	remaining: 777ms
130:	learn: 0.1711054	total: 117ms	remaining: 775ms
131:	learn: 0.1708650	total: 118ms	remaining: 773ms
132:	learn: 0.1707007	total: 118ms	remaining: 771ms
133:	learn: 0.1705119	total: 119ms	remaining: 770ms
134:	learn: 0.1703635	total: 120ms	remaining: 771ms
135:	learn: 0.1702263	total: 121ms	remaining: 770ms
136:	learn: 0.1700259	total: 122ms	remaining: 768ms
137:	learn: 0.1698808	total: 123ms	remaining: 766ms
138:	learn: 0.1697669	total: 123ms	remaining: 763ms
139:	learn: 0.1696081	total: 125ms	remaining: 765ms
140:	learn: 0.1694774	total: 125ms	remaining: 763ms
141:	learn: 0.1692192	total: 126ms	remaining: 762ms
142:	learn: 0.1689628	total: 127ms	remaining: 760ms
143:	learn: 0.1687926	total: 128ms	remaining: 759ms
144:	learn: 0.1686752	total: 128ms	remaining: 757ms
145:	learn: 0.1684344	total: 129ms	remaining: 756ms
146:	learn: 0.1681574	total: 130ms	remaining: 754ms
147:	learn: 0.1679282	total: 131ms	remaining: 753ms
148:	learn: 0.1677975	total: 132ms	remaining: 751ms
149:	learn: 0.1675044	total: 132ms	remaining: 749ms
150:	learn: 0.1672119	total: 133ms	remaining: 748ms
151:	learn: 0.1670755	total: 134ms	remaining: 746ms
152:	learn: 0.1668981	total: 134ms	remaining: 744ms
153:	learn: 0.1668181	total: 135ms	remaining: 743ms
154:	learn: 0.1665007	total: 136ms	remaining: 742ms
155:	learn: 0.1663092	total: 137ms	remaining: 740ms
156:	learn: 0.1660817	total: 138ms	remaining: 739ms
157:	learn: 0.1659693	total: 138ms	remaining: 737ms
158:	learn: 0.1658327	total: 139ms	remaining: 736ms
159:	learn: 0.1657047	total: 140ms	remaining: 735ms
160:	learn: 0.1655077	total: 141ms	remaining: 733ms
161:	learn: 0.1653866	total: 142ms	remaining: 736ms
162:	learn: 0.1652349	total: 143ms	remaining: 734ms
163:	learn: 0.1649743	total: 144ms	remaining: 733ms
164:	learn: 0.1647799	total: 145ms	remaining: 732ms
165:	learn: 0.1646385	total: 145ms	remaining: 730ms
166:	learn: 0.1644777	total: 146ms	remaining: 729ms
167:	learn: 0.1642447	total: 147ms	remaining: 727ms
168:	learn: 0.1640652	total: 148ms	remaining: 726ms
169:	learn: 0.1639109	total: 148ms	remaining: 725ms
170:	learn: 0.1637870	total: 149ms	remaining: 723ms
171:	learn: 0.1636217	total: 150ms	remaining: 721ms
172:	learn: 0.1635465	total: 151ms	remaining: 720ms
173:	learn: 0.1635028	total: 151ms	remaining: 717ms
174:	learn: 0.1633498	total: 152ms	remaining: 716ms
175:	learn: 0.1631939	total: 153ms	remaining: 715ms
176:	learn: 0.1630304	total: 153ms	remaining: 713ms
177:	learn: 0.1628898	total: 154ms	remaining: 712ms
178:	learn: 0.1627667	total: 155ms	remaining: 710ms
179:	learn: 0.1626245	total: 156ms	remaining: 709ms
180:	learn: 0.1625336	total: 156ms	remaining: 708ms
181:	learn: 0.1624086	total: 157ms	remaining: 706ms
182:	learn: 0.1622055	total: 158ms	remaining: 705ms
183:	learn: 0.1619499	total: 159ms	remaining: 703ms
184:	learn: 0.1618278	total: 159ms	remaining: 702ms
185:	learn: 0.1616408	total: 160ms	remaining: 701ms
186:	learn: 0.1614928	total: 161ms	remaining: 699ms
187:	learn: 0.1613551	total: 162ms	remaining: 698ms
188:	learn: 0.1612003	total: 162ms	remaining: 696ms
189:	learn: 0.1610318	total: 163ms	remaining: 695ms
190:	learn: 0.1609123	total: 164ms	remaining: 693ms
191:	learn: 0.1608216	total: 164ms	remaining: 692ms
192:	learn: 0.1607558	total: 166ms	remaining: 695ms
193:	learn: 0.1606062	total: 167ms	remaining: 694ms
194:	learn: 0.1603610	total: 168ms	remaining: 692ms
195:	learn: 0.1601942	total: 168ms	remaining: 691ms
196:	learn: 0.1600241	total: 169ms	remaining: 689ms
197:	learn: 0.1599330	total: 170ms	remaining: 688ms
198:	learn: 0.1597804	total: 171ms	remaining: 687ms
199:	learn: 0.1596835	total: 171ms	remaining: 686ms
200:	learn: 0.1596198	total: 172ms	remaining: 684ms
201:	learn: 0.1595244	total: 173ms	remaining: 683ms
202:	learn: 0.1594415	total: 174ms	remaining: 682ms
203:	learn: 0.1593566	total: 174ms	remaining: 681ms
204:	learn: 0.1591860	total: 175ms	remaining: 679ms
205:	learn: 0.1589958	total: 176ms	remaining: 678ms
206:	learn: 0.1588798	total: 177ms	remaining: 676ms
207:	learn: 0.1587744	total: 177ms	remaining: 675ms
208:	learn: 0.1586454	total: 178ms	remaining: 674ms
209:	learn: 0.1583702	total: 179ms	remaining: 672ms
210:	learn: 0.1582807	total: 179ms	remaining: 671ms
211:	learn: 0.1579866	total: 180ms	remaining: 670ms
212:	learn: 0.1578612	total: 181ms	remaining: 669ms
213:	learn: 0.1576961	total: 182ms	remaining: 667ms
214:	learn: 0.1575237	total: 182ms	remaining: 666ms
215:	learn: 0.1574320	total: 183ms	remaining: 665ms
216:	learn: 0.1572100	total: 184ms	remaining: 664ms
217:	learn: 0.1570473	total: 185ms	remaining: 663ms
218:	learn: 0.1569500	total: 186ms	remaining: 663ms
219:	learn: 0.1568771	total: 187ms	remaining: 662ms
220:	learn: 0.1567647	total: 187ms	remaining: 660ms
221:	learn: 0.1566866	total: 188ms	remaining: 659ms
222:	learn: 0.1565484	total: 189ms	remaining: 658ms
223:	learn: 0.1564303	total: 191ms	remaining: 661ms
224:	learn: 0.1562728	total: 192ms	remaining: 660ms
225:	learn: 0.1560657	total: 192ms	remaining: 659ms
226:	learn: 0.1559758	total: 193ms	remaining: 658ms
227:	learn: 0.1558985	total: 194ms	remaining: 657ms
228:	learn: 0.1557992	total: 195ms	remaining: 656ms
229:	learn: 0.1556927	total: 195ms	remaining: 654ms
230:	learn: 0.1554600	total: 196ms	remaining: 653ms
231:	learn: 0.1553830	total: 197ms	remaining: 652ms
232:	learn: 0.1552614	total: 198ms	remaining: 651ms
233:	learn: 0.1551789	total: 198ms	remaining: 649ms
234:	learn: 0.1551182	total: 199ms	remaining: 648ms
235:	learn: 0.1550600	total: 200ms	remaining: 647ms
236:	learn: 0.1549530	total: 201ms	remaining: 646ms
237:	learn: 0.1548188	total: 201ms	remaining: 645ms
238:	learn: 0.1547304	total: 203ms	remaining: 645ms
239:	learn: 0.1546035	total: 203ms	remaining: 645ms
240:	learn: 0.1543932	total: 203ms	remaining: 643ms
241:	learn: 0.1542966	total: 204ms	remaining: 642ms
242:	learn: 0.1541978	total: 205ms	remaining: 642ms
243:	learn: 0.1541413	total: 206ms	remaining: 641ms
244:	learn: 0.1539987	total: 207ms	remaining: 640ms
245:	learn: 0.1538513	total: 207ms	remaining: 639ms
246:	learn: 0.1536944	total: 208ms	remaining: 637ms
247:	learn: 0.1535654	total: 209ms	remaining: 636ms
248:	learn: 0.1533802	total: 210ms	remaining: 635ms
249:	learn: 0.1533180	total: 210ms	remaining: 634ms
250:	learn: 0.1531620	total: 211ms	remaining: 632ms
251:	learn: 0.1530152	total: 212ms	remaining: 631ms
252:	learn: 0.1529569	total: 212ms	remaining: 630ms
253:	learn: 0.1529020	total: 213ms	remaining: 629ms
254:	learn: 0.1528497	total: 214ms	remaining: 628ms
255:	learn: 0.1527391	total: 215ms	remaining: 627ms
256:	learn: 0.1526796	total: 216ms	remaining: 626ms
257:	learn: 0.1524773	total: 216ms	remaining: 625ms
258:	learn: 0.1523345	total: 217ms	remaining: 624ms
259:	learn: 0.1521685	total: 218ms	remaining: 622ms
260:	learn: 0.1520481	total: 219ms	remaining: 621ms
261:	learn: 0.1518744	total: 219ms	remaining: 620ms
262:	learn: 0.1517287	total: 220ms	remaining: 619ms
263:	learn: 0.1516593	total: 221ms	remaining: 618ms
264:	learn: 0.1515312	total: 221ms	remaining: 616ms
265:	learn: 0.1514542	total: 222ms	remaining: 615ms
266:	learn: 0.1513136	total: 223ms	remaining: 614ms
267:	learn: 0.1512152	total: 224ms	remaining: 613ms
268:	learn: 0.1511802	total: 224ms	remaining: 612ms
269:	learn: 0.1510587	total: 226ms	remaining: 612ms
270:	learn: 0.1509498	total: 226ms	remaining: 611ms
271:	learn: 0.1508430	total: 227ms	remaining: 610ms
272:	learn: 0.1507359	total: 228ms	remaining: 609ms
273:	learn: 0.1506278	total: 229ms	remaining: 608ms
274:	learn: 0.1505064	total: 229ms	remaining: 607ms
275:	learn: 0.1503493	total: 230ms	remaining: 606ms
276:	learn: 0.1502341	total: 231ms	remaining: 605ms
277:	learn: 0.1501244	total: 232ms	remaining: 604ms
278:	learn: 0.1499461	total: 232ms	remaining: 603ms
279:	learn: 0.1498611	total: 233ms	remaining: 602ms
280:	learn: 0.1496856	total: 234ms	remaining: 600ms
281:	learn: 0.1495741	total: 235ms	remaining: 599ms
282:	learn: 0.1494349	total: 235ms	remaining: 598ms
283:	learn: 0.1493412	total: 236ms	remaining: 597ms
284:	learn: 0.1492931	total: 237ms	remaining: 596ms
285:	learn: 0.1490897	total: 238ms	remaining: 595ms
286:	learn: 0.1489013	total: 238ms	remaining: 594ms
287:	learn: 0.1487441	total: 239ms	remaining: 593ms
288:	learn: 0.1486916	total: 240ms	remaining: 592ms
289:	learn: 0.1485316	total: 241ms	remaining: 591ms
290:	learn: 0.1484881	total: 241ms	remaining: 590ms
291:	learn: 0.1483673	total: 242ms	remaining: 589ms
292:	learn: 0.1483180	total: 243ms	remaining: 588ms
293:	learn: 0.1481998	total: 244ms	remaining: 588ms
294:	learn: 0.1480878	total: 245ms	remaining: 587ms
295:	learn: 0.1479794	total: 245ms	remaining: 585ms
296:	learn: 0.1478174	total: 246ms	remaining: 585ms
297:	learn: 0.1477337	total: 247ms	remaining: 584ms
298:	learn: 0.1475861	total: 248ms	remaining: 583ms
299:	learn: 0.1474736	total: 248ms	remaining: 582ms
300:	learn: 0.1472999	total: 249ms	remaining: 580ms
301:	learn: 0.1471156	total: 250ms	remaining: 580ms
302:	learn: 0.1470142	total: 251ms	remaining: 579ms
303:	learn: 0.1468685	total: 252ms	remaining: 578ms
304:	learn: 0.1466336	total: 253ms	remaining: 578ms
305:	learn: 0.1465744	total: 253ms	remaining: 576ms
306:	learn: 0.1464318	total: 254ms	remaining: 575ms
307:	learn: 0.1463426	total: 255ms	remaining: 574ms
308:	learn: 0.1462556	total: 256ms	remaining: 573ms
309:	learn: 0.1461894	total: 256ms	remaining: 572ms
310:	learn: 0.1461457	total: 257ms	remaining: 571ms
311:	learn: 0.1460456	total: 258ms	remaining: 570ms
312:	learn: 0.1459684	total: 258ms	remaining: 569ms
313:	learn: 0.1458425	total: 259ms	remaining: 568ms
314:	learn: 0.1456370	total: 260ms	remaining: 567ms
315:	learn: 0.1455247	total: 261ms	remaining: 566ms
316:	learn: 0.1454873	total: 262ms	remaining: 565ms
317:	learn: 0.1453692	total: 262ms	remaining: 564ms
318:	learn: 0.1452705	total: 263ms	remaining: 563ms
319:	learn: 0.1450321	total: 264ms	remaining: 562ms
320:	learn: 0.1449184	total: 265ms	remaining: 562ms
321:	learn: 0.1448187	total: 266ms	remaining: 561ms
322:	learn: 0.1447258	total: 267ms	remaining: 560ms
323:	learn: 0.1446679	total: 267ms	remaining: 559ms
324:	learn: 0.1445636	total: 268ms	remaining: 559ms
325:	learn: 0.1444851	total: 269ms	remaining: 558ms
326:	learn: 0.1443541	total: 270ms	remaining: 557ms
327:	learn: 0.1441497	total: 271ms	remaining: 556ms
328:	learn: 0.1439861	total: 271ms	remaining: 555ms
329:	learn: 0.1438302	total: 272ms	remaining: 555ms
330:	learn: 0.1437257	total: 273ms	remaining: 554ms
331:	learn: 0.1436274	total: 274ms	remaining: 553ms
332:	learn: 0.1435319	total: 275ms	remaining: 552ms
333:	learn: 0.1433500	total: 275ms	remaining: 551ms
334:	learn: 0.1432482	total: 276ms	remaining: 550ms
335:	learn: 0.1431019	total: 277ms	remaining: 549ms
336:	learn: 0.1429668	total: 278ms	remaining: 548ms
337:	learn: 0.1428570	total: 278ms	remaining: 547ms
338:	learn: 0.1427201	total: 279ms	remaining: 546ms
339:	learn: 0.1426426	total: 280ms	remaining: 545ms
340:	learn: 0.1425533	total: 281ms	remaining: 544ms
341:	learn: 0.1424678	total: 282ms	remaining: 543ms
342:	learn: 0.1423999	total: 282ms	remaining: 542ms
343:	learn: 0.1422927	total: 283ms	remaining: 541ms
344:	learn: 0.1422021	total: 284ms	remaining: 540ms
345:	learn: 0.1421536	total: 284ms	remaining: 539ms
346:	learn: 0.1420311	total: 285ms	remaining: 538ms
347:	learn: 0.1419427	total: 286ms	remaining: 537ms
348:	learn: 0.1418495	total: 287ms	remaining: 536ms
349:	learn: 0.1417090	total: 287ms	remaining: 535ms
350:	learn: 0.1416229	total: 288ms	remaining: 534ms
351:	learn: 0.1415592	total: 289ms	remaining: 533ms
352:	learn: 0.1413906	total: 290ms	remaining: 532ms
353:	learn: 0.1413178	total: 290ms	remaining: 531ms
354:	learn: 0.1412431	total: 291ms	remaining: 530ms
355:	learn: 0.1411753	total: 292ms	remaining: 529ms
356:	learn: 0.1410975	total: 292ms	remaining: 528ms
357:	learn: 0.1410126	total: 293ms	remaining: 527ms
358:	learn: 0.1408385	total: 294ms	remaining: 526ms
359:	learn: 0.1407627	total: 295ms	remaining: 525ms
360:	learn: 0.1406703	total: 295ms	remaining: 524ms
361:	learn: 0.1405620	total: 296ms	remaining: 524ms
362:	learn: 0.1404547	total: 297ms	remaining: 523ms
363:	learn: 0.1403693	total: 298ms	remaining: 522ms
364:	learn: 0.1403259	total: 298ms	remaining: 521ms
365:	learn: 0.1401395	total: 299ms	remaining: 520ms
366:	learn: 0.1400404	total: 300ms	remaining: 519ms
367:	learn: 0.1398927	total: 301ms	remaining: 518ms
368:	learn: 0.1398074	total: 302ms	remaining: 517ms
369:	learn: 0.1397158	total: 302ms	remaining: 516ms
370:	learn: 0.1396374	total: 303ms	remaining: 515ms
371:	learn: 0.1395275	total: 304ms	remaining: 514ms
372:	learn: 0.1394307	total: 304ms	remaining: 513ms
373:	learn: 0.1393453	total: 305ms	remaining: 512ms
374:	learn: 0.1392868	total: 306ms	remaining: 511ms
375:	learn: 0.1392044	total: 307ms	remaining: 510ms
376:	learn: 0.1390742	total: 307ms	remaining: 509ms
377:	learn: 0.1389539	total: 308ms	remaining: 508ms
378:	learn: 0.1388212	total: 309ms	remaining: 507ms
379:	learn: 0.1387243	total: 310ms	remaining: 507ms
380:	learn: 0.1386323	total: 310ms	remaining: 506ms
381:	learn: 0.1385631	total: 312ms	remaining: 505ms
382:	learn: 0.1385311	total: 313ms	remaining: 505ms
383:	learn: 0.1383961	total: 313ms	remaining: 504ms

In [85]:
score_df = pd.DataFrame.from_dict(scores).T

In [86]:
score_df

                                MSE      RMSE       MAE        R2
LinearRegression           0.049582  0.222671  0.162846  0.843033
Ridge                      0.049571  0.222646  0.162793  0.843068
Lasso                      0.315984  0.562125  0.429485 -0.000344
DecisionTreeRegressor      0.049796  0.223150  0.144856  0.842356
SVR                        0.039569  0.198919  0.143812  0.874733
GradientBoostingRegressor  0.030445  0.174485  0.127159  0.903617
RandomForestRegressor      0.028223  0.167996  0.112568  0.910653
AdaBoostRegressor          0.048659  0.220588  0.169438  0.845956
XGBRegressor               0.029004  0.170305  0.111988  0.908180
CatBoostRegressor          0.027169  0.164831  0.113981  0.913987
LGBMRegressor              0.028726  0.169487  0.116702  0.909059

In [93]:
rt = automac.autotune.RegressionTuner(x=x_s , y=y_transformed)

In [95]:
tuner = rt.tune()

🚀 Starting Parallel Regression Tuning for: ['rf', 'xgb', 'lgb', 'cat', 'ada', 'dt', 'svm', 'knn']
✅ Tuning complete!

In [98]:
tuner

{'RandomForest': ({'n_estimators': 367,
   'max_depth': 26,
   'min_samples_split': 3},
  0.026411244355693544),
 'XGBoost': ({'n_estimators': 237,
   'learning_rate': 0.019641970874481877,
   'max_depth': 10,
   'subsample': 0.5951790412625925},
  0.02497368591429559),
 'LightGBM': ({'n_estimators': 594,
   'learning_rate': 0.013110298768911692,
   'num_leaves': 239},
  0.026702286688606077),
 'CatBoost': ({'iterations': 682,
   'depth': 8,
   'learning_rate': 0.12652258428307456},
  0.02525169532949082),
 'AdaBoost': ({'n_estimators': 142,
   'learning_rate': 0.5801159711340872,
   'loss': 'square'},
  0.04243367075029896),
 'DecisionTree': ({'max_depth': 6, 'criterion': 'squared_error'},
  0.041428303683500506),
 'SVM': ({'C': 1.9385488953385204,
   'epsilon': 0.09011252083486063,
   'kernel': 'rbf'},
  0.039524708599615155),
 'KNN': ({'n_neighbors': 6, 'weights': 'distance'}, 0.04472574051885287)}

In [105]:
tuner['KNN'][0]

{'n_neighbors': 6, 'weights': 'distance'}

In [114]:
from sklearn.neighbors import KNeighborsRegressor
models2 = [RandomForestRegressor(**tuner['RandomForest'][0]) , XGBRegressor(**tuner['XGBoost'][0]) , LGBMRegressor(**tuner['LightGBM'][0]) , CatBoostRegressor(**tuner['CatBoost'][0]) , AdaBoostRegressor(**tuner['AdaBoost'][0]) , DecisionTreeRegressor(**tuner['DecisionTree'][0]) , SVR(**tuner['SVM'][0]) , KNeighborsRegressor(**tuner['KNN'][0])]

names2 =list(tuner.keys())

In [136]:
scores2 = {}
traned_models = []
for i in range(len(models2)):
    score2 = ra.regression_metrics(model=models2[i])
    traned_models.append(models2[i]) 
    scores2[names2[i]] = score2

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000148 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 409
[LightGBM] [Info] Number of data points in the train set: 2487, number of used features: 12
[LightGBM] [Info] Start training from score 1.043280
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [123]:
score_df2 = pd.DataFrame.from_dict(scores2).T
score_df2

                   MSE      RMSE       MAE        R2
RandomForest  0.027509  0.165858  0.110808  0.912912
XGBoost       0.026561  0.162975  0.109459  0.915914
LightGBM      0.028150  0.167780  0.113669  0.910883
CatBoost      0.027693  0.166413  0.113018  0.912329
AdaBoost      0.049407  0.222276  0.169142  0.843589
DecisionTree  0.040879  0.202185  0.147933  0.870585
SVM           0.039021  0.197536  0.142718  0.876469
KNN           0.050145  0.223930  0.149158  0.841252

In [129]:
score_df2.sort_values(by='MAE')

                   MSE      RMSE       MAE        R2
XGBoost       0.026561  0.162975  0.109459  0.915914
RandomForest  0.027509  0.165858  0.110808  0.912912
CatBoost      0.027693  0.166413  0.113018  0.912329
LightGBM      0.028150  0.167780  0.113669  0.910883
SVM           0.039021  0.197536  0.142718  0.876469
DecisionTree  0.040879  0.202185  0.147933  0.870585
KNN           0.050145  0.223930  0.149158  0.841252
AdaBoost      0.049407  0.222276  0.169142  0.843589

In [131]:
for model in models2:
    ra.plot_regression_results(model)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000113 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 408
[LightGBM] [Info] Number of data points in the train set: 2487, number of used features: 12
[LightGBM] [Info] Start training from score 1.043498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

0:	learn: 0.5159454	total: 3.2ms	remaining: 2.18s
1:	learn: 0.4683460	total: 4.93ms	remaining: 1.68s
2:	learn: 0.4262810	total: 6.46ms	remaining: 1.46s
3:	learn: 0.3893749	total: 7.9ms	remaining: 1.34s
4:	learn: 0.3577620	total: 9.32ms	remaining: 1.26s
5:	learn: 0.3311119	total: 11.2ms	remaining: 1.26s
6:	learn: 0.3088451	total: 12.9ms	remaining: 1.24s
7:	learn: 0.2888375	total: 14.5ms	remaining: 1.23s
8:	learn: 0.2720891	total: 16ms	remaining: 1.2s
9:	learn: 0.2580564	total: 17.8ms	remaining: 1.19s
10:	learn: 0.2453420	total: 19.5ms	remaining: 1.19s
11:	learn: 0.2352589	total: 21.3ms	remaining: 1.19s
12:	learn: 0.2271975	total: 22.9ms	remaining: 1.18s
13:	learn: 0.2195340	total: 24.9ms	remaining: 1.19s
14:	learn: 0.2127885	total: 26.8ms	remaining: 1.19s
15:	learn: 0.2070481	total: 28.4ms	remaining: 1.18s
16:	learn: 0.2022779	total: 30.7ms	remaining: 1.2s
17:	learn: 0.1974682	total: 32.9ms	remaining: 1.21s
18:	learn: 0.1937296	total: 35.1ms	remaining: 1.23s
19:	learn: 0.1900679	total: 37.3ms	remaining: 1.24s
20:	learn: 0.1872822	total: 39.6ms	remaining: 1.25s
21:	learn: 0.1849860	total: 42ms	remaining: 1.26s
22:	learn: 0.1821527	total: 43.6ms	remaining: 1.25s
23:	learn: 0.1803756	total: 45.2ms	remaining: 1.24s
24:	learn: 0.1782469	total: 46.8ms	remaining: 1.23s
25:	learn: 0.1766415	total: 48.3ms	remaining: 1.22s
26:	learn: 0.1750019	total: 50.1ms	remaining: 1.22s
27:	learn: 0.1730984	total: 51.8ms	remaining: 1.21s
28:	learn: 0.1713442	total: 53.4ms	remaining: 1.2s
29:	learn: 0.1697586	total: 55.5ms	remaining: 1.21s
30:	learn: 0.1686571	total: 57.6ms	remaining: 1.21s
31:	learn: 0.1677161	total: 59.4ms	remaining: 1.21s
32:	learn: 0.1666730	total: 61.8ms	remaining: 1.22s
33:	learn: 0.1655507	total: 63.9ms	remaining: 1.22s
34:	learn: 0.1643742	total: 65.8ms	remaining: 1.22s
35:	learn: 0.1629504	total: 67.7ms	remaining: 1.22s
36:	learn: 0.1622156	total: 69.5ms	remaining: 1.21s
37:	learn: 0.1615208	total: 71.5ms	remaining: 1.21s
38:	learn: 0.1604488	total: 73.2ms	remaining: 1.21s
39:	learn: 0.1596857	total: 74.8ms	remaining: 1.2s
40:	learn: 0.1587637	total: 76.3ms	remaining: 1.19s
41:	learn: 0.1578270	total: 77.8ms	remaining: 1.19s
42:	learn: 0.1570010	total: 79.8ms	remaining: 1.19s
43:	learn: 0.1562582	total: 81.9ms	remaining: 1.19s
44:	learn: 0.1561159	total: 82.6ms	remaining: 1.17s
45:	learn: 0.1553034	total: 84.2ms	remaining: 1.16s
46:	learn: 0.1549660	total: 86.8ms	remaining: 1.17s
47:	learn: 0.1545198	total: 88.7ms	remaining: 1.17s
48:	learn: 0.1535650	total: 91.2ms	remaining: 1.18s
49:	learn: 0.1529760	total: 93ms	remaining: 1.18s
50:	learn: 0.1523714	total: 94.7ms	remaining: 1.17s
51:	learn: 0.1515990	total: 96.8ms	remaining: 1.17s
52:	learn: 0.1510415	total: 98.6ms	remaining: 1.17s
53:	learn: 0.1506762	total: 100ms	remaining: 1.16s
54:	learn: 0.1502966	total: 102ms	remaining: 1.16s
55:	learn: 0.1498582	total: 103ms	remaining: 1.15s
56:	learn: 0.1489047	total: 105ms	remaining: 1.15s
57:	learn: 0.1485823	total: 106ms	remaining: 1.14s
58:	learn: 0.1482844	total: 107ms	remaining: 1.13s
59:	learn: 0.1479766	total: 109ms	remaining: 1.13s
60:	learn: 0.1475202	total: 110ms	remaining: 1.12s
61:	learn: 0.1471701	total: 112ms	remaining: 1.12s
62:	learn: 0.1465391	total: 114ms	remaining: 1.12s
63:	learn: 0.1462409	total: 114ms	remaining: 1.12s
64:	learn: 0.1457868	total: 115ms	remaining: 1.11s
65:	learn: 0.1449842	total: 117ms	remaining: 1.11s
66:	learn: 0.1444549	total: 119ms	remaining: 1.1s
67:	learn: 0.1440773	total: 120ms	remaining: 1.1s
68:	learn: 0.1438641	total: 122ms	remaining: 1.1s
69:	learn: 0.1434289	total: 123ms	remaining: 1.09s
70:	learn: 0.1429778	total: 125ms	remaining: 1.09s
71:	learn: 0.1424562	total: 126ms	remaining: 1.09s
72:	learn: 0.1417579	total: 128ms	remaining: 1.08s
73:	learn: 0.1413951	total: 130ms	remaining: 1.08s
74:	learn: 0.1410169	total: 131ms	remaining: 1.08s
75:	learn: 0.1405649	total: 133ms	remaining: 1.07s
76:	learn: 0.1402632	total: 135ms	remaining: 1.07s
77:	learn: 0.1397836	total: 137ms	remaining: 1.08s
78:	learn: 0.1391468	total: 139ms	remaining: 1.07s
79:	learn: 0.1386149	total: 141ms	remaining: 1.07s
80:	learn: 0.1381713	total: 142ms	remaining: 1.07s
81:	learn: 0.1377769	total: 144ms	remaining: 1.07s
82:	learn: 0.1374908	total: 146ms	remaining: 1.07s
83:	learn: 0.1372114	total: 148ms	remaining: 1.06s
84:	learn: 0.1369627	total: 150ms	remaining: 1.06s
85:	learn: 0.1365152	total: 151ms	remaining: 1.06s
86:	learn: 0.1361811	total: 153ms	remaining: 1.06s
87:	learn: 0.1356763	total: 155ms	remaining: 1.05s
88:	learn: 0.1350087	total: 156ms	remaining: 1.05s
89:	learn: 0.1347796	total: 158ms	remaining: 1.05s
90:	learn: 0.1342369	total: 160ms	remaining: 1.05s
91:	learn: 0.1339078	total: 162ms	remaining: 1.05s
92:	learn: 0.1336242	total: 164ms	remaining: 1.05s
93:	learn: 0.1334555	total: 165ms	remaining: 1.04s
94:	learn: 0.1331575	total: 167ms	remaining: 1.04s
95:	learn: 0.1325258	total: 169ms	remaining: 1.04s
96:	learn: 0.1323743	total: 171ms	remaining: 1.04s
97:	learn: 0.1316388	total: 172ms	remaining: 1.04s
98:	learn: 0.1313668	total: 174ms	remaining: 1.03s
99:	learn: 0.1308742	total: 176ms	remaining: 1.03s
100:	learn: 0.1304209	total: 177ms	remaining: 1.03s
101:	learn: 0.1300503	total: 179ms	remaining: 1.03s
102:	learn: 0.1294469	total: 181ms	remaining: 1.03s
103:	learn: 0.1291877	total: 183ms	remaining: 1.03s
104:	learn: 0.1285459	total: 185ms	remaining: 1.02s
105:	learn: 0.1283678	total: 186ms	remaining: 1.02s
106:	learn: 0.1278690	total: 188ms	remaining: 1.02s
107:	learn: 0.1273851	total: 190ms	remaining: 1.02s
108:	learn: 0.1268273	total: 192ms	remaining: 1.02s
109:	learn: 0.1265460	total: 194ms	remaining: 1.02s
110:	learn: 0.1259966	total: 196ms	remaining: 1.02s
111:	learn: 0.1255618	total: 198ms	remaining: 1.01s
112:	learn: 0.1252910	total: 200ms	remaining: 1.01s
113:	learn: 0.1249487	total: 202ms	remaining: 1.01s
114:	learn: 0.1244364	total: 203ms	remaining: 1.01s
115:	learn: 0.1240074	total: 205ms	remaining: 1.01s
116:	learn: 0.1235787	total: 207ms	remaining: 1.01s
117:	learn: 0.1231869	total: 208ms	remaining: 1s
118:	learn: 0.1228111	total: 210ms	remaining: 1s
119:	learn: 0.1223445	total: 212ms	remaining: 1s
120:	learn: 0.1221975	total: 214ms	remaining: 1s
121:	learn: 0.1216172	total: 216ms	remaining: 1s
122:	learn: 0.1212733	total: 218ms	remaining: 998ms
123:	learn: 0.1207536	total: 219ms	remaining: 995ms
124:	learn: 0.1203079	total: 221ms	remaining: 993ms
125:	learn: 0.1200559	total: 223ms	remaining: 991ms
126:	learn: 0.1198106	total: 225ms	remaining: 989ms
127:	learn: 0.1195621	total: 226ms	remaining: 987ms
128:	learn: 0.1191145	total: 228ms	remaining: 985ms
129:	learn: 0.1189258	total: 230ms	remaining: 983ms
130:	learn: 0.1184298	total: 231ms	remaining: 981ms
131:	learn: 0.1181419	total: 233ms	remaining: 978ms
132:	learn: 0.1176654	total: 234ms	remaining: 975ms
133:	learn: 0.1170544	total: 236ms	remaining: 973ms
134:	learn: 0.1166665	total: 238ms	remaining: 971ms
135:	learn: 0.1162289	total: 240ms	remaining: 969ms
136:	learn: 0.1159916	total: 241ms	remaining: 967ms
137:	learn: 0.1153846	total: 243ms	remaining: 965ms
138:	learn: 0.1149675	total: 245ms	remaining: 962ms
139:	learn: 0.1147016	total: 246ms	remaining: 960ms
140:	learn: 0.1142979	total: 248ms	remaining: 958ms
141:	learn: 0.1139437	total: 250ms	remaining: 956ms
142:	learn: 0.1137561	total: 251ms	remaining: 954ms
143:	learn: 0.1135275	total: 253ms	remaining: 952ms
144:	learn: 0.1132520	total: 255ms	remaining: 950ms
145:	learn: 0.1129169	total: 256ms	remaining: 947ms
146:	learn: 0.1127543	total: 259ms	remaining: 947ms
147:	learn: 0.1123862	total: 261ms	remaining: 947ms
148:	learn: 0.1120945	total: 262ms	remaining: 945ms
149:	learn: 0.1117982	total: 264ms	remaining: 943ms
150:	learn: 0.1114469	total: 266ms	remaining: 941ms
151:	learn: 0.1110101	total: 267ms	remaining: 938ms
152:	learn: 0.1106880	total: 269ms	remaining: 936ms
153:	learn: 0.1104311	total: 271ms	remaining: 934ms
154:	learn: 0.1101061	total: 272ms	remaining: 931ms
155:	learn: 0.1097335	total: 274ms	remaining: 929ms
156:	learn: 0.1093291	total: 275ms	remaining: 927ms
157:	learn: 0.1091542	total: 277ms	remaining: 924ms
158:	learn: 0.1090052	total: 278ms	remaining: 922ms
159:	learn: 0.1087548	total: 280ms	remaining: 919ms
160:	learn: 0.1083468	total: 281ms	remaining: 917ms
161:	learn: 0.1081960	total: 283ms	remaining: 914ms
162:	learn: 0.1079481	total: 285ms	remaining: 912ms
163:	learn: 0.1077827	total: 286ms	remaining: 910ms
164:	learn: 0.1075819	total: 288ms	remaining: 907ms
165:	learn: 0.1074022	total: 289ms	remaining: 905ms
166:	learn: 0.1070050	total: 291ms	remaining: 902ms
167:	learn: 0.1068820	total: 292ms	remaining: 899ms
168:	learn: 0.1066278	total: 294ms	remaining: 897ms
169:	learn: 0.1064004	total: 295ms	remaining: 894ms
170:	learn: 0.1061276	total: 297ms	remaining: 892ms
171:	learn: 0.1058601	total: 298ms	remaining: 889ms
172:	learn: 0.1057240	total: 300ms	remaining: 887ms
173:	learn: 0.1056019	total: 301ms	remaining: 884ms
174:	learn: 0.1051581	total: 303ms	remaining: 882ms
175:	learn: 0.1049779	total: 304ms	remaining: 879ms
176:	learn: 0.1046547	total: 306ms	remaining: 877ms
177:	learn: 0.1042554	total: 307ms	remaining: 874ms
178:	learn: 0.1040265	total: 307ms	remaining: 874ms
179:	learn: 0.1036440	total: 308ms	remaining: 870ms
180:	learn: 0.1032285	total: 310ms	remaining: 867ms
181:	learn: 0.1029171	total: 311ms	remaining: 864ms
182:	learn: 0.1025946	total: 313ms	remaining: 863ms
183:	learn: 0.1023802	total: 314ms	remaining: 860ms
184:	learn: 0.1020794	total: 316ms	remaining: 857ms
185:	learn: 0.1017868	total: 317ms	remaining: 855ms
186:	learn: 0.1014252	total: 318ms	remaining: 852ms
187:	learn: 0.1012050	total: 320ms	remaining: 849ms
188:	learn: 0.1009461	total: 321ms	remaining: 847ms
189:	learn: 0.1006379	total: 323ms	remaining: 844ms
190:	learn: 0.1004615	total: 324ms	remaining: 842ms
191:	learn: 0.1002177	total: 326ms	remaining: 839ms
192:	learn: 0.1000759	total: 327ms	remaining: 837ms
193:	learn: 0.0999553	total: 328ms	remaining: 834ms
194:	learn: 0.0995998	total: 330ms	remaining: 832ms
195:	learn: 0.0994023	total: 331ms	remaining: 830ms
196:	learn: 0.0992349	total: 333ms	remaining: 829ms
197:	learn: 0.0990250	total: 335ms	remaining: 827ms
198:	learn: 0.0988543	total: 337ms	remaining: 827ms
199:	learn: 0.0987623	total: 339ms	remaining: 825ms
200:	learn: 0.0986059	total: 340ms	remaining: 823ms
201:	learn: 0.0984179	total: 342ms	remaining: 820ms
202:	learn: 0.0980102	total: 343ms	remaining: 817ms
203:	learn: 0.0979186	total: 344ms	remaining: 815ms
204:	learn: 0.0974673	total: 346ms	remaining: 812ms
205:	learn: 0.0974061	total: 347ms	remaining: 811ms
206:	learn: 0.0971933	total: 349ms	remaining: 808ms
207:	learn: 0.0969632	total: 350ms	remaining: 806ms
208:	learn: 0.0967223	total: 352ms	remaining: 803ms
209:	learn: 0.0964674	total: 353ms	remaining: 801ms
210:	learn: 0.0962225	total: 354ms	remaining: 799ms
211:	learn: 0.0960347	total: 356ms	remaining: 796ms
212:	learn: 0.0957122	total: 357ms	remaining: 794ms
213:	learn: 0.0954843	total: 358ms	remaining: 791ms
214:	learn: 0.0953615	total: 360ms	remaining: 789ms
215:	learn: 0.0952615	total: 362ms	remaining: 788ms
216:	learn: 0.0950003	total: 363ms	remaining: 786ms
217:	learn: 0.0948166	total: 365ms	remaining: 784ms
218:	learn: 0.0945860	total: 366ms	remaining: 781ms
219:	learn: 0.0943978	total: 368ms	remaining: 779ms
220:	learn: 0.0942482	total: 369ms	remaining: 776ms
221:	learn: 0.0940696	total: 370ms	remaining: 774ms
222:	learn: 0.0939521	total: 372ms	remaining: 772ms
223:	learn: 0.0936513	total: 373ms	remaining: 770ms
224:	learn: 0.0935283	total: 375ms	remaining: 768ms
225:	learn: 0.0933091	total: 376ms	remaining: 765ms
226:	learn: 0.0930051	total: 377ms	remaining: 763ms
227:	learn: 0.0927966	total: 379ms	remaining: 761ms
228:	learn: 0.0926058	total: 380ms	remaining: 759ms
229:	learn: 0.0924403	total: 382ms	remaining: 757ms
230:	learn: 0.0923170	total: 383ms	remaining: 755ms
231:	learn: 0.0921488	total: 385ms	remaining: 753ms
232:	learn: 0.0919619	total: 386ms	remaining: 751ms
233:	learn: 0.0917151	total: 388ms	remaining: 749ms
234:	learn: 0.0915981	total: 390ms	remaining: 748ms
235:	learn: 0.0914618	total: 391ms	remaining: 746ms
236:	learn: 0.0912708	total: 393ms	remaining: 744ms
237:	learn: 0.0911252	total: 395ms	remaining: 742ms
238:	learn: 0.0909138	total: 396ms	remaining: 741ms
239:	learn: 0.0907029	total: 398ms	remaining: 739ms
240:	learn: 0.0905480	total: 400ms	remaining: 737ms
241:	learn: 0.0903867	total: 401ms	remaining: 736ms
242:	learn: 0.0900754	total: 403ms	remaining: 734ms
243:	learn: 0.0898495	total: 404ms	remaining: 732ms
244:	learn: 0.0896017	total: 406ms	remaining: 730ms
245:	learn: 0.0893578	total: 408ms	remaining: 728ms
246:	learn: 0.0891728	total: 409ms	remaining: 727ms
247:	learn: 0.0889750	total: 411ms	remaining: 725ms
248:	learn: 0.0887268	total: 413ms	remaining: 723ms
249:	learn: 0.0886056	total: 414ms	remaining: 722ms
250:	learn: 0.0884261	total: 416ms	remaining: 720ms
251:	learn: 0.0883062	total: 418ms	remaining: 718ms
252:	learn: 0.0881033	total: 419ms	remaining: 717ms
253:	learn: 0.0879635	total: 421ms	remaining: 715ms
254:	learn: 0.0877531	total: 423ms	remaining: 713ms
255:	learn: 0.0876018	total: 424ms	remaining: 712ms
256:	learn: 0.0874060	total: 426ms	remaining: 710ms
257:	learn: 0.0871438	total: 428ms	remaining: 708ms
258:	learn: 0.0869105	total: 429ms	remaining: 707ms
259:	learn: 0.0868318	total: 431ms	remaining: 705ms
260:	learn: 0.0867381	total: 433ms	remaining: 703ms
261:	learn: 0.0866356	total: 434ms	remaining: 701ms
262:	learn: 0.0865289	total: 436ms	remaining: 699ms
263:	learn: 0.0863238	total: 437ms	remaining: 698ms
264:	learn: 0.0860654	total: 439ms	remaining: 696ms
265:	learn: 0.0859171	total: 440ms	remaining: 694ms
266:	learn: 0.0858256	total: 442ms	remaining: 692ms
267:	learn: 0.0857118	total: 444ms	remaining: 690ms
268:	learn: 0.0855978	total: 445ms	remaining: 688ms
269:	learn: 0.0854818	total: 446ms	remaining: 686ms
270:	learn: 0.0852905	total: 448ms	remaining: 684ms
271:	learn: 0.0850540	total: 449ms	remaining: 682ms
272:	learn: 0.0849437	total: 450ms	remaining: 680ms
273:	learn: 0.0848304	total: 452ms	remaining: 678ms
274:	learn: 0.0846902	total: 453ms	remaining: 676ms
275:	learn: 0.0845859	total: 455ms	remaining: 674ms
276:	learn: 0.0845043	total: 456ms	remaining: 672ms
277:	learn: 0.0843917	total: 458ms	remaining: 670ms
278:	learn: 0.0842048	total: 459ms	remaining: 668ms
279:	learn: 0.0839607	total: 461ms	remaining: 666ms
280:	learn: 0.0837271	total: 462ms	remaining: 664ms
281:	learn: 0.0835979	total: 464ms	remaining: 662ms
282:	learn: 0.0834046	total: 465ms	remaining: 660ms
283:	learn: 0.0831517	total: 467ms	remaining: 658ms
284:	learn: 0.0829532	total: 468ms	remaining: 656ms
285:	learn: 0.0827493	total: 470ms	remaining: 655ms
286:	learn: 0.0826048	total: 471ms	remaining: 653ms
287:	learn: 0.0824578	total: 473ms	remaining: 651ms
288:	learn: 0.0822707	total: 475ms	remaining: 650ms
289:	learn: 0.0820687	total: 476ms	remaining: 648ms
290:	learn: 0.0818277	total: 478ms	remaining: 647ms
291:	learn: 0.0816019	total: 480ms	remaining: 645ms
292:	learn: 0.0815138	total: 481ms	remaining: 644ms
293:	learn: 0.0813723	total: 483ms	remaining: 642ms
294:	learn: 0.0812162	total: 485ms	remaining: 640ms
295:	learn: 0.0811271	total: 487ms	remaining: 639ms
296:	learn: 0.0810303	total: 489ms	remaining: 638ms
297:	learn: 0.0808556	total: 492ms	remaining: 638ms
298:	learn: 0.0807709	total: 493ms	remaining: 636ms
299:	learn: 0.0805997	total: 495ms	remaining: 635ms
300:	learn: 0.0805075	total: 497ms	remaining: 633ms
301:	learn: 0.0802564	total: 498ms	remaining: 631ms
302:	learn: 0.0801704	total: 500ms	remaining: 630ms
303:	learn: 0.0799966	total: 502ms	remaining: 628ms
304:	learn: 0.0798505	total: 503ms	remaining: 626ms
305:	learn: 0.0796445	total: 505ms	remaining: 625ms
306:	learn: 0.0794369	total: 507ms	remaining: 623ms
307:	learn: 0.0793677	total: 508ms	remaining: 621ms
308:	learn: 0.0793009	total: 510ms	remaining: 620ms
309:	learn: 0.0791459	total: 511ms	remaining: 618ms
310:	learn: 0.0790530	total: 513ms	remaining: 616ms
311:	learn: 0.0789290	total: 515ms	remaining: 614ms
312:	learn: 0.0788249	total: 516ms	remaining: 612ms
313:	learn: 0.0787438	total: 518ms	remaining: 611ms
314:	learn: 0.0785736	total: 519ms	remaining: 609ms
315:	learn: 0.0783690	total: 521ms	remaining: 607ms
316:	learn: 0.0781628	total: 522ms	remaining: 605ms
317:	learn: 0.0780734	total: 524ms	remaining: 604ms
318:	learn: 0.0779119	total: 526ms	remaining: 602ms
319:	learn: 0.0778286	total: 527ms	remaining: 600ms
320:	learn: 0.0776793	total: 529ms	remaining: 598ms
321:	learn: 0.0776299	total: 530ms	remaining: 597ms
322:	learn: 0.0775150	total: 532ms	remaining: 595ms
323:	learn: 0.0774261	total: 533ms	remaining: 593ms
324:	learn: 0.0773406	total: 535ms	remaining: 591ms
325:	learn: 0.0771405	total: 536ms	remaining: 589ms
326:	learn: 0.0770297	total: 538ms	remaining: 588ms
327:	learn: 0.0768760	total: 540ms	remaining: 586ms
328:	learn: 0.0768314	total: 541ms	remaining: 584ms
329:	learn: 0.0767203	total: 543ms	remaining: 582ms
330:	learn: 0.0766232	total: 544ms	remaining: 581ms
331:	learn: 0.0765127	total: 546ms	remaining: 579ms
332:	learn: 0.0763702	total: 547ms	remaining: 577ms
333:	learn: 0.0762088	total: 549ms	remaining: 575ms
334:	learn: 0.0761626	total: 551ms	remaining: 574ms
335:	learn: 0.0760076	total: 552ms	remaining: 572ms
336:	learn: 0.0758471	total: 554ms	remaining: 570ms
337:	learn: 0.0756972	total: 556ms	remaining: 569ms
338:	learn: 0.0755536	total: 557ms	remaining: 567ms
339:	learn: 0.0752799	total: 559ms	remaining: 565ms
340:	learn: 0.0751121	total: 560ms	remaining: 564ms
341:	learn: 0.0748873	total: 562ms	remaining: 562ms
342:	learn: 0.0747840	total: 564ms	remaining: 560ms
343:	learn: 0.0746782	total: 565ms	remaining: 559ms
344:	learn: 0.0744761	total: 567ms	remaining: 557ms
345:	learn: 0.0743575	total: 569ms	remaining: 556ms
346:	learn: 0.0742349	total: 570ms	remaining: 554ms
347:	learn: 0.0742002	total: 572ms	remaining: 552ms
348:	learn: 0.0740767	total: 574ms	remaining: 550ms
349:	learn: 0.0739202	total: 575ms	remaining: 549ms
350:	learn: 0.0738240	total: 577ms	remaining: 547ms
351:	learn: 0.0736778	total: 578ms	remaining: 545ms
352:	learn: 0.0736301	total: 580ms	remaining: 544ms
353:	learn: 0.0734555	total: 582ms	remaining: 542ms
354:	learn: 0.0732437	total: 583ms	remaining: 540ms
355:	learn: 0.0731492	total: 585ms	remaining: 539ms
356:	learn: 0.0730420	total: 587ms	remaining: 537ms
357:	learn: 0.0729224	total: 588ms	remaining: 535ms
358:	learn: 0.0728336	total: 590ms	remaining: 534ms
359:	learn: 0.0727421	total: 591ms	remaining: 532ms
360:	learn: 0.0726434	total: 593ms	remaining: 530ms
361:	learn: 0.0725227	total: 595ms	remaining: 529ms
362:	learn: 0.0724335	total: 596ms	remaining: 527ms
363:	learn: 0.0723730	total: 598ms	remaining: 525ms
364:	learn: 0.0722912	total: 599ms	remaining: 524ms
365:	learn: 0.0721965	total: 601ms	remaining: 522ms
366:	learn: 0.0720570	total: 603ms	remaining: 520ms
367:	learn: 0.0719783	total: 604ms	remaining: 518ms
368:	learn: 0.0717085	total: 606ms	remaining: 517ms
369:	learn: 0.0716004	total: 608ms	remaining: 515ms
370:	learn: 0.0715159	total: 609ms	remaining: 514ms
371:	learn: 0.0714025	total: 611ms	remaining: 512ms
372:	learn: 0.0711712	total: 613ms	remaining: 510ms
373:	learn: 0.0710633	total: 614ms	remaining: 509ms
374:	learn: 0.0709119	total: 616ms	remaining: 507ms
375:	learn: 0.0707207	total: 617ms	remaining: 505ms
376:	learn: 0.0706339	total: 619ms	remaining: 503ms
377:	learn: 0.0705473	total: 621ms	remaining: 502ms
378:	learn: 0.0704111	total: 623ms	remaining: 500ms
379:	learn: 0.0703379	total: 624ms	remaining: 499ms
380:	learn: 0.0702219	total: 626ms	remaining: 497ms
381:	learn: 0.0701335	total: 627ms	remaining: 495ms
382:	learn: 0.0699592	total: 629ms	remaining: 494ms
383:	learn: 0.0698090	total: 631ms	remaining: 492ms
384:	learn: 0.0696857	total: 632ms	remaining: 490ms
385:	learn: 0.0695358	total: 634ms	remaining: 489ms

In [132]:
scaler

StandardScaler()

In [134]:
encoder

TargetEncoder(cols=['agePossession', 'luxury_category', 'floor_category',
                    'sector', 'property_type', 'balcony'])

In [135]:
tuner

{'RandomForest': ({'n_estimators': 367,
   'max_depth': 26,
   'min_samples_split': 3},
  0.026411244355693544),
 'XGBoost': ({'n_estimators': 237,
   'learning_rate': 0.019641970874481877,
   'max_depth': 10,
   'subsample': 0.5951790412625925},
  0.02497368591429559),
 'LightGBM': ({'n_estimators': 594,
   'learning_rate': 0.013110298768911692,
   'num_leaves': 239},
  0.026702286688606077),
 'CatBoost': ({'iterations': 682,
   'depth': 8,
   'learning_rate': 0.12652258428307456},
  0.02525169532949082),
 'AdaBoost': ({'n_estimators': 142,
   'learning_rate': 0.5801159711340872,
   'loss': 'square'},
  0.04243367075029896),
 'DecisionTree': ({'max_depth': 6, 'criterion': 'squared_error'},
  0.041428303683500506),
 'SVM': ({'C': 1.9385488953385204,
   'epsilon': 0.09011252083486063,
   'kernel': 'rbf'},
  0.039524708599615155),
 'KNN': ({'n_neighbors': 6, 'weights': 'distance'}, 0.04472574051885287)}

In [138]:
traned_models[0]

RandomForestRegressor(max_depth=26, min_samples_split=3, n_estimators=367)

In [139]:
import pickle

with open('encoder.pkl', 'wb') as file:
    pickle.dump(encoder, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

with open('models.pkl', 'wb') as file:
    pickle.dump(traned_models, file)

In [140]:
df

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3549,flat,sector 84,0.37,2.0,2.0,1,Relatively New,532.0,0.0,0.0,0.0,Medium,Mid Floor
3550,house,sector 109,6.00,5.0,5.0,3+,Relatively New,6228.0,1.0,1.0,0.0,High,Low Floor
3551,flat,sector 2,0.60,1.0,1.0,1,Moderately Old,665.0,0.0,0.0,1.0,Medium,Mid Floor
3552,house,sector 43,15.50,5.0,6.0,3,Moderately Old,5490.0,1.0,1.0,0.0,Medium,Mid Floor
3553,flat,sector 68,1.78,3.0,3.0,3+,Relatively New,1845.0,0.0,0.0,1.0,Medium,High Floor

In [141]:
with open('df.pkl', 'wb') as file:
    pickle.dump(df, file)

In [142]:
encoder

TargetEncoder(cols=['agePossession', 'luxury_category', 'floor_category',
                    'sector', 'property_type', 'balcony'])

In [145]:
traned_models[:4]

[RandomForestRegressor(max_depth=26, min_samples_split=3, n_estimators=367),
 XGBRegressor(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.019641970874481877, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=237, n_jobs=None,
              num_parallel_tree=None, ...),
 LGBMRegressor(learning_rate=0.013110298768911692, n_estimators=594,
               num_leaves=239),
 CatBoostRegressor(depth=8, iterations=682, learning_rate=0.12652258428307456, loss_function='RMSE')]

In [152]:
encoder.feature_names_out_

array(['agePossession', 'luxury_category', 'floor_category', 'sector',
       'property_type', 'balcony'], dtype=object)

In [166]:
row = X.iloc[[1]]  # double brackets preserve DataFrame structure
row_encoded = encoder.transform(row)
row_e = scaler.transform(row['built_up_area'].values.reshape(-1 ,1))

In [160]:
row

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
1,flat,sector 89,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor

In [168]:
row_e

array([[1226.]])

In [172]:
scaler.transform(row)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- agePossession
- balcony
- bathroom
- bedRoom
- floor_category
- ...

In [176]:
x_s.columns

Index(['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category'],
      dtype='str')

In [ ]:
Index(['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category'],
      dtype='str')