In [1]:
print("Let's Start")

Let's Start

In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv('gurgaon_properties.csv')

In [5]:
df.sample(5)

                         property_name property_type                     society  price  price_per_sqft    area                                       areaWithType  bedRoom  bathroom balcony additionalRoom                                            address  floorNum      facing     agePossession                                    nearbyLocations                                        description                                     furnishDetails                                           features                                             rating
2619  3 BHK Flat in Sector 102 Gurgaon          flat        emaar gurgaon greens   1.40          8484.0  1650.0  Super Built up area 1650(153.29 sq.m.)Carpet a...        3         3       3   servant room  Flat Number 601, Sector 102 Gurgaon, Gurgaon, ...       3.0        East   1 to 5 Year Old  ['JMS Marine Square Mall', 'Dwarka Expressway'...  Emaar gurgaon greens in sector 102, gurgaon is...                                                NaN  ['Power Back-up', 'Intercom Facility', 'Lift(s...  ['Green Area5 out of 5', 'Construction4 out of...
1593  3 BHK Flat in Sector 37D Gurgaon          flat  ramprastha the edge towers   1.00          5649.0  1770.0             Super Built up area 1770(164.44 sq.m.)        3         3      3+            NaN               Sector 37D Gurgaon, Gurgaon, Haryana      13.0         NaN  5 to 10 Year Old  ['MDS Public School', 'St Pauls School', 'Sunc...   It semi- Furnished wardrobes and modular kitchen                                                 []  ['Power Back-up', 'Intercom Facility', 'Lift(s...  ['Green Area4 out of 5', 'Construction4 out of...
3696   3 BHK Flat in Sector 84 Gurgaon          flat            ss the coralwood   1.10          4857.0  2265.0             Super Built up area 1750(162.58 sq.m.)        3         3       2            NaN                Sector 84 Gurgaon, Gurgaon, Haryana       9.0       North   1 to 5 Year Old  ['Sapphire 83 Mall', 'Sector 84 Road', 'Dwarka...  Ss the coralwood is offering a 3bhk apartment ...  ['1 Light', 'No AC', 'No Bed', 'No Chimney', '...  ['Feng Shui / Vaastu Compliant', 'Intercom Fac...  ['Green Area4 out of 5', 'Construction4 out of...
837   2 BHK Flat in Sector 108 Gurgaon          flat      experion the heartsong   0.97          9238.0  1050.0                    Carpet area: 1050 (97.55 sq.m.)        2         2       3   servant room               Sector 108 Gurgaon, Gurgaon, Haryana      10.0  North-East   1 to 5 Year Old  ['Galleria 108 Mall', 'Dwarka Expressway', 'Ce...  This lovely 2 bhk apartment/flat in sector 108...                                                 []  ['Water purifier', 'Security / Fire Alarm', 'F...  ['Green Area5 out of 5', 'Construction4 out of...
1269   3 BHK Flat in Sector 54 Gurgaon          flat              dlf park place   4.86         25920.0  1875.0             Super Built up area 1875(174.19 sq.m.)        3         4      3+   servant room                Sector 54 Gurgaon, Gurgaon, Haryana       7.0        West   1 to 5 Year Old  ['Sector 53-54 Metro Station', 'Sector 54 Chow...  Dlf park place is one of gurgaon's most sought...  ['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...  ['Feng Shui / Vaastu Compliant', 'Security / F...  ['Green Area5 out of 5', 'Construction5 out of...

In [6]:
df.shape

(3961, 20)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   str
 1   property_type    3961 non-null   str
 2   society          3960 non-null   str
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   str
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   str
 10  additionalRoom   2270 non-null   str
 11  address          3950 non-null   str
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   str
 14  agePossession    3960 non-null   str
 15  nearbyLocations  3754 non-null   str
 16  description      3961 non-null   str
 17  furnishDetails   2929 non-null   str
 18  features         3252 non-null   str
 19  rating           3511 non-null   str
dtypes: float64(4), int64(2), str(14)
memory usage: 6.9 MB

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom     1691
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [10]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 59 Gurgaon,flat,mahindra luminare,5.50,18181.0,3025.0,Super Built up area 3025(281.03 sq.m.),3,3,1,servant room,"Sector 59 Gurgaon, Gurgaon, Haryana",26.0,NaN,Dec 2024,"['Sector 55-56 Metro Station', 'Metro World Ma...",Located in the popular residential address of ...,"['4 Fan', '4 Light', '4 AC', '1 Modular Kitche...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley,1.79,11251.0,1591.0,Super Built up area 1789(166.2 sq.m.),3,3,3,NaN,"B Tower, Sector-33 Sohna, Gurgaon, Haryana",3.0,South,10+ Year Old,"['Golf Course Extension Rd', 'Rajiv Chowk - So...",Aqua facing unit luxury unit ! Parking all inc...,"['3 Wardrobe', '4 AC', '1 Modular Kitchen', 'N...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'H...",NaN
2,3 Bedroom House for sale in Rosewood,house,independent,2.95,16388.0,1800.0,Plot area 1800(167.23 sq.m.)Built Up area: 190...,3,3,3,store room,3 Bhk With 3 Bath Independent Villa For Sale A...,2.0,North-West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",Well maintained owner self living 3 bhk with 3...,"['3 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,4 Bedroom House for sale in DLF Phase 2,house,dlf city plots phase 2,6.30,35000.0,1800.0,Plot area 200(167.23 sq.m.),4,4,3+,"servant room,store room","Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...",This is a four bedroom house in dlf phase - 2 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
4,4 Bedroom House for sale in Arjun Nagar,house,independent,0.82,10224.0,802.0,Carpet area: 802 (74.51 sq.m.),4,4,0,NaN,"Arjun Nagar, Gurgaon, Haryana, India, Arjun Na...",2.0,NaN,undefined,"['Lal Superspeciality Hospital', 'Shri Gobind ...",An independant 2 storey well maintained house ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [11]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [12]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 59 Gurgaon,flat,mahindra luminare,Sector 59,5.50,18181.0,3025.0,Super Built up area 3025(281.03 sq.m.),3,3,1,servant room,"Sector 59 Gurgaon, Gurgaon, Haryana",26.0,NaN,Dec 2024,"['Sector 55-56 Metro Station', 'Metro World Ma...",Located in the popular residential address of ...,"['4 Fan', '4 Light', '4 AC', '1 Modular Kitche...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley,Sector-33 Sohna,1.79,11251.0,1591.0,Super Built up area 1789(166.2 sq.m.),3,3,3,NaN,"B Tower, Sector-33 Sohna, Gurgaon, Haryana",3.0,South,10+ Year Old,"['Golf Course Extension Rd', 'Rajiv Chowk - So...",Aqua facing unit luxury unit ! Parking all inc...,"['3 Wardrobe', '4 AC', '1 Modular Kitchen', 'N...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'H...",NaN
2,3 Bedroom House for sale in Rosewood,house,independent,Rosewood,2.95,16388.0,1800.0,Plot area 1800(167.23 sq.m.)Built Up area: 190...,3,3,3,store room,3 Bhk With 3 Bath Independent Villa For Sale A...,2.0,North-West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",Well maintained owner self living 3 bhk with 3...,"['3 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,4 Bedroom House for sale in DLF Phase 2,house,dlf city plots phase 2,DLF Phase 2,6.30,35000.0,1800.0,Plot area 200(167.23 sq.m.),4,4,3+,"servant room,store room","Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...",This is a four bedroom house in dlf phase - 2 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
4,4 Bedroom House for sale in Arjun Nagar,house,independent,Arjun Nagar,0.82,10224.0,802.0,Carpet area: 802 (74.51 sq.m.),4,4,0,NaN,"Arjun Nagar, Gurgaon, Haryana, India, Arjun Na...",2.0,NaN,undefined,"['Lal Superspeciality Hospital', 'Shri Gobind ...",An independant 2 storey well maintained house ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [13]:
df['sector'] = df['sector'].str.lower()

In [14]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 59 Gurgaon,flat,mahindra luminare,sector 59,5.50,18181.0,3025.0,Super Built up area 3025(281.03 sq.m.),3,3,1,servant room,"Sector 59 Gurgaon, Gurgaon, Haryana",26.0,NaN,Dec 2024,"['Sector 55-56 Metro Station', 'Metro World Ma...",Located in the popular residential address of ...,"['4 Fan', '4 Light', '4 AC', '1 Modular Kitche...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley,sector-33 sohna,1.79,11251.0,1591.0,Super Built up area 1789(166.2 sq.m.),3,3,3,NaN,"B Tower, Sector-33 Sohna, Gurgaon, Haryana",3.0,South,10+ Year Old,"['Golf Course Extension Rd', 'Rajiv Chowk - So...",Aqua facing unit luxury unit ! Parking all inc...,"['3 Wardrobe', '4 AC', '1 Modular Kitchen', 'N...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'H...",NaN
2,3 Bedroom House for sale in Rosewood,house,independent,rosewood,2.95,16388.0,1800.0,Plot area 1800(167.23 sq.m.)Built Up area: 190...,3,3,3,store room,3 Bhk With 3 Bath Independent Villa For Sale A...,2.0,North-West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",Well maintained owner self living 3 bhk with 3...,"['3 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,4 Bedroom House for sale in DLF Phase 2,house,dlf city plots phase 2,dlf phase 2,6.30,35000.0,1800.0,Plot area 200(167.23 sq.m.),4,4,3+,"servant room,store room","Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...",This is a four bedroom house in dlf phase - 2 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
4,4 Bedroom House for sale in Arjun Nagar,house,independent,arjun nagar,0.82,10224.0,802.0,Carpet area: 802 (74.51 sq.m.),4,4,0,NaN,"Arjun Nagar, Gurgaon, Haryana, India, Arjun Na...",2.0,NaN,undefined,"['Lal Superspeciality Hospital', 'Shri Gobind ...",An independant 2 storey well maintained house ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [15]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 37c                                                    53
nirvana country                                               53
sector 70                                                     53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
sector 113                                                    43
dlf phase 1                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 111                                                    22
dlf phase 3                                                   22
sector 67a                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sushant lok phase 3                                           16
sector 99                                                     16
sector 14                                                     15
sector 63                                                     15
sector 60                                                     15
sector 52                                                     14
sector 1 imt manesar                                          14
sector 76                                                     14
dlf phase 5                                                   14
rajendra park                                                 14
gwal pahari                                                   14
sector 3                                                      14
sector 53                                                     14
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
sohna road                                                    12
sector 38                                                     12
sector 93                                                     12
sector 39                                                     12
sector 50                                                     12
sector 31                                                     12
uppals southend                                               12
sector 47                                                     11
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 4                                                       9
sector 95a                                                     9
south city 1                                                   9
ashok vihar phase 2                                            9
sector 55                                                      9
sector 59                                                      8
sector 57                                                      8
sector 40                                                      8
sector 43                                                      8
c block sushant lok phase 1                                    8
sector 10a                                                     8
dwarka expressway                                              8
malibu town                                                    8
mehrauli  road                                                 8
sector 89 a                                                    8
palam vihar extension                                          8
sector 58                                                      7
new colony                                                     7
sector 11                                                      7
surat nagar 1                                                  7
sector 36 sohna                                                7
sector 51                                                      7
mianwali colony                                                7
sector 26                                                      7
jyoti park                                                     6
sector 1                                                       6
ashok vihar                                                    6
rajiv nagar                                                    6
jacobpura                                                      6
sector 5                                                       6
arjun nagar                                                    5
ansal plaza                                                    5
sector 30                                                      5
sector 105                                                     5
sector 28                                                      5
saraswati vihar                                                5
sushant lok phase 2                                            5
sector 9                                                       5
sector 23a                                                     5
greenwood city                                                 5
sector 80                                                      5
manesar                                                        5
chakkarpur                                                     5
subhash nagar                                                  5
sector 2                                                       5
new palam vihar                                                5
dayanand colony                                                5
valley view estate                                             4
bhondsi                                                        4
sector 36                                                      4
sector 12a                                                     4
sector 3a                                                      4
surya vihar                                                    4
madanpuri                                                      4
dharam colony                                                  4
shivpuri                                                       4
sector 45                                                      4
sector 12                                                      4
krishna colony                                                 4
ravi nagar                                                     4
shivaji nagar                                                  4
bhim nagar                                                     4
devilal colony                                                 4
imt manesar                                                    4
baldev nagar                                                   4
sector 17                                                      4
suncity                                                        4
vishnu garden                                                  4
garhi harsaru                                                  4
sector 6                                                       4
new                                                            4
adarsh nagar                                                   4
sector 27                                                      3
sector 17b                                                     3
prem nagar                                                     3
sector 8                                                       3
sector 73                                                      3
maruti kunj                                                    3
mg road                                                        3
sector 17a                                                     3
shakti nagar                                                   3
sector 88b                                                     3
laxmi garden                                                   3
sector 15                                                      3
b block sushant lok phase 1                                    3
sector 23                                                      3
sector 110 a                                                   3
patel nagar                                                    3
a block sushant lok phase 1                                    3
gandhi nagar                                                   3
rosewood                                                       2
golf course road                                               2
block a surya vihar                                            2
new basti                                                      2
pratap nagar                                                   2
golf course ext road                                           2
sector-2 sohna                                                 2
iffco chowk                                                    2
shankar vihar                                                  2
farukhnagar                                                    2
new palam vihar phase 1                                        2
sheetla colony                                                 2
sector 24                                                      2
sispal vihar                                                   2
bhawani enclave                                                2
sector 15 part 1                                               2
bissar                                                         2
surat nagar phase 2                                            2
surat nagar                                                    2
samaspur                                                       2
shanti nagar                                                   2
ambience island                                                2
, delhi ncr                                                    2
daulatabad                                                     2
hira nagar                                                     2
new palam vihar phase 2                                        2
sushant lok                                                    2
mayfield garden                                                2
acharya puri                                                   2
manohar nagar                                                  2
rajiv chowk                                                    2
sector 41                                                      2
nars                                                           2
sohna  road                                                    2
mohan nagar                                                    2
sector 32                                                      2
sector-11 sohna                                                2
faridabad road                                                 2
sector 15 part 2                                               2
sector 21                                                      2
west rajiv nagar                                               2
lajpat nagar                                                   2
ravi nager basai road                                          1
park view                                                      1
sector-7 hous                                                  1
part 3 sector 5                                                1
south city                                                     1
rajiv colony                                                   1
near pataudi chowk                                             1
sector-35 sohna                                                1
naharpur rupa                                                  1
gopal nagar, garhi ghasita, sonipat                            1
saroop garden rajendra park                                    1
block g sector-57                                              1
hsiidc plot sector 1 imt manesar                               1
ansal's palam vihar                                            1
heritage city                                                  1
bhora kalan                                                    1
sector-5 sohna                                                 1
near khandsa road                                              1
ashok vihar phase 3                                            1
cyber city                                                     1
bhimgarh kheri phase 3                                         1
urban estate, sector 5                                         1
near nand hospital                                             1
b1 block sector 57                                             1
mahavir pura                                                   1
bptp                                                           1
sultanpur                                                      1
new jyoti park                                                 1
rattan garden                                                  1
ram nagar                                                      1
new colony, sector 7                                           1
block h ashok vihar phase iii extension                        1
jat colony,fazilpur/taj nagar road                             1
sector 13                                                      1
sector 4 urban estate                                          1
sector 37a                                                     1
sector 9b                                                      1
kheri                                                          1
devi lal colony gali no 12 gurgaon nr omkar public school      1
begampur khatola                                               1
laxmna vihar, phase 2                                          1
carterpuri village                                             1
sadar bazar                                                    1
nirvana country pocket h                                       1
godrej aria , sector 79 ,                                      1
om nagar                                                       1
damdma                                                         1
udyog vihar phase 1                                            1
sec 3 bhim vihar part 1 bhimgher kheri                         1
laxman vihar, railway road,                                    1
civil l                                                        1
khandsa                                                        1
alipur                                                         1
sector 5 chowk                                                 1
ashok vihar phase i                                            1
kanahi                                                         1
mahalaxmi garden, rajendra place                               1
lucknow                                                        1
dhankot                                                        1
saraswati enclave                                              1
sector 42                                                      1
sai kunj                                                       1
ats marigold                                                   1
shivji park colony                                             1
old delhi road, opp sector-14                                  1
jacobpura near sadar bazar                                     1
vir nagar                                                      1
sector 17c                                                     1
garauli kalan                                                  1
sector 21a faridabad                                           1
g block dlf city phase 1                                       1
near sector 1 market                                           1
hno 13 sagar enclave sura                                      1
anand garden, sector-105                                       1
sector 37b                                                     1
huda saraswati vihar                                           1
pataudi road                                                   1
near euro                                                      1
tekchand nagar                                                 1
sector-5 sheetla colony                                        1
v block dlf phase 3                                            1
Name: count, dtype: int64

In [16]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [17]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [18]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [19]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [20]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [21]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [22]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [23]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [24]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 90                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 37c                     53
sector 70                      53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 82                      42
sector 61                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 24                      24
sector 57                      24
sector 112                     24
sector 105                     23
sector 33                      23
sector 14                      23
sector 88a                     23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 82a                     20
sector 3                       20
sector 22                      20
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 62                      17
sector 91                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 52                      14
sector 1 manesar               14
sector 76                      14
sector 53                      14
sector 55                      14
sector 46                      13
sector 36a                     13
sector 9                       13
sector 4 phase 2               13
sector 6                       13
sohna road road                12
sector 38                      12
sector 93                      12
sector 39                      12
sector 31                      12
sector 3 phase 3 extension     11
sector 41                      11
sector 9a                      11
sector 13                      10
sector 1a manesar              10
sector 95a                      9
sector 45                       9
sector 3 phase 2                9
manesar                         9
sector 59                       8
sector 8                        8
sector 23                       8
sector 40                       8
c block sector 43               8
sector 10a                      8
dwarka expressway               8
sector 17                       8
sector 89 a                     8
sector 2 extension              8
sector 58                       7
sector 36 sohna road            7
sector 51                       7
sector 21                       6
sector 1                        6
sector 5                        6
sector 30                       5
sector 23a                      5
sector 80                       5
new sector 2                    5
sector 36                       4
sector 12a                      4
sector 3a                       4
new                             4
sector 27                       3
sector 17b                      3
sector 73                       3
maruti kunj                     3
sector 17a                      3
sector 88b                      3
sector 15                       3
b block sector 43               3
sector 110 a                    3
patel nagar                     3
a block sector 43               3
Name: count, dtype: int64

In [25]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [26]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [27]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1461,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,NaN,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2994,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
3362,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,NaN,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3547,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,NaN,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [28]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [29]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1483,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,NaN,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1681,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,NaN,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
1728,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,NaN,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2534,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3421,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [30]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [31]:
df.shape

(3803, 21)

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.head()

                             property_name property_type                     society           sector  price  price_per_sqft    area                            areaWithType  bedRoom  bathroom balcony           additionalRoom                                            address  floorNum facing     agePossession                                    nearbyLocations                                        description                                     furnishDetails                                           features                                             rating
0          3 BHK Flat in Sector 59 Gurgaon          flat           mahindra luminare        sector 59   5.50         18181.0  3025.0  Super Built up area 3025(281.03 sq.m.)        3         3       1             servant room                Sector 59 Gurgaon, Gurgaon, Haryana      26.0    NaN          Dec 2024  ['Sector 55-56 Metro Station', 'Metro World Ma...  Located in the popular residential address of ...  ['4 Fan', '4 Light', '4 AC', '1 Modular Kitche...  ['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...  ['Green Area5 out of 5', 'Construction5 out of...
1            3 BHK Flat in Sector-33 Sohna          flat  central park flower valley        sector 33   1.79         11251.0  1591.0   Super Built up area 1789(166.2 sq.m.)        3         3       3                      NaN         B Tower, Sector-33 Sohna, Gurgaon, Haryana       3.0  South      10+ Year Old  ['Golf Course Extension Rd', 'Rajiv Chowk - So...  Aqua facing unit luxury unit ! Parking all inc...  ['3 Wardrobe', '4 AC', '1 Modular Kitchen', 'N...  ['Feng Shui / Vaastu Compliant', 'Lift(s)', 'H...                                                NaN
3  4 Bedroom House for sale in DLF Phase 2         house      dlf city plots phase 2        sector 25   6.30         35000.0  1800.0             Plot area 200(167.23 sq.m.)        4         4      3+  servant room,store room         Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana       2.0   East      10+ Year Old  ['Sahara Mall', 'Delhi Public School', 'Privat...  This is a four bedroom house in dlf phase - 2 ...                                                NaN  ['Feng Shui / Vaastu Compliant', 'Private Gard...  ['Environment5 out of 5', 'Safety5 out of 5', ...
4  4 Bedroom House for sale in Arjun Nagar         house                 independent         sector 8   0.82         10224.0   802.0          Carpet area: 802 (74.51 sq.m.)        4         4       0                      NaN  Arjun Nagar, Gurgaon, Haryana, India, Arjun Na...       2.0    NaN         undefined  ['Lal Superspeciality Hospital', 'Shri Gobind ...  An independant 2 storey well maintained house ...  ['1 Light', 'No AC', 'No Bed', 'No Chimney', '...                                                NaN  ['Environment4 out of 5', 'Lifestyle4 out of 5...
5   2 Bedroom House for sale in Sohna Road         house                 independent  sohna road road   0.50          5555.0   900.0              Plot area 900(83.61 sq.m.)        2         1       2                      NaN                       Sohna Road, Gurgaon, Haryana       1.0    NaN  5 to 10 Year Old  ['Rajiv Chowk Mosque', 'Standard chartered ATM...  I am looking for buyer to purchase house/villa...                                                 []                                                NaN                                                NaN

In [34]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [35]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
1223,house,dlf city plots phase 2,sector 25,10.55,39074.0,2700.0,Plot area 300(250.84 sq.m.),5,6,3+,"pooja room,study room,servant room,store room",3.0,East,5 to 10 Year Old,"['Vodafone belvedere towers metro station', 'D...","['4 Geyser', '5 Light', '1 Chimney', 'No AC', ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
3794,flat,godrej,sector 79,2.50,11141.0,2244.0,Built Up area: 2244 (208.47 sq.m.)Carpet area:...,3,3,3+,NaN,5.0,NaN,undefined,"['Vatika Town Square-INXT', 'Naurangpur Road',...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
3914,flat,vipul lavanya,sector 81,0.65,5265.0,1235.0,Super Built up area 1225(113.81 sq.m.)Carpet a...,2,2,2,NaN,14.0,NaN,5 to 10 Year Old,"['Orris Community Center', 'Petrol Pump', 'HP ...","['2 Wardrobe', '4 Fan', '5 Light', 'No AC', 'N...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2827,flat,ireo victory valley,sector 67,2.95,12235.0,2411.0,Super Built up area 2411(223.99 sq.m.)Carpet a...,3,3,3,servant room,10.0,North-West,1 to 5 Year Old,"['AIPL Joy Street Mall', 'Golf Course Extensio...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'..."
3270,flat,mariners home,sector 56,2.11,8612.0,2450.0,Super Built up area 2450(227.61 sq.m.)Built Up...,3,2,3,others,4.0,South,1 to 5 Year Old,"['Sector 54 chowk metro station', 'Sector metr...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '21 Lig...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [36]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [37]:
df.duplicated().sum()

np.int64(121)

In [38]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)